FROM golang:1.22.5-bullseye AS builder

COPY . /opt
RUN cd /opt && go build -o bin/producer cmd/producer/main.go

FROM debian:bullseye
RUN apt update && apt-get install ca-certificates -y
RUN adduser --gecos "Devops Starboard,Github,WorkPhone,HomePhone" --home /app/data-notify-server --disabled-password spacescope
USER spacescope
COPY --from=builder /opt/bin/producer /app/data-notify-server/data-notify-server

CMD ["--conf", "/app/data-notify-server/service.conf"]
ENTRYPOINT ["/app/data-notify-server/data-notify-server"]
